name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 SSH Agent
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. 添加远程主机到 known_hosts
      - name: Add remote host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      # 4. 测试 SSH 连接（可选但推荐）
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "echo ✅ SSH connection successful"

      # 5. 复制文件到服务器
      - name: Copy file to server
        run: |
          scp -o StrictHostKeyChecking=no ./Openvpn.sh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/root/openvpn-install.sh
          echo "✅ Script deployed successfully!"
